# -*- coding: utf-8 -*-
"""
config.py: The configuration file of SAP2000 to Ruamoko converter.
"""

# Define which DoFs are on (1) or off (0) for the nodal weights definitions, 
# e.g. {1 0 1 0 1 0} means the node has non-zero horizontal translational weight
# and non-zero vertical rotational inertia (i.e. rotation about vertical axis)
weights_dofs = {'ux':1, 'uy':0, 'uz':1, 'rx':0, 'ry':1, 'rz':0}

# Define which DoFs are on (1) or off (0) for the nodal static loads definitions, 
# e.g. {0 1 0 0 0 0} means the node only has vertical static load applied to it
loads_dofs = {'ux':0, 'uy':1, 'uz':0, 'rx':0, 'ry':0, 'rz':0}

#_____________________________________________________________________________#

"""
Define keywords specific to the .s2k file format exported by SAP2000. This is to 
ensure compatibility with later versions of SAP2000. Edit these variables to 
match the output of the .s2k file.

Last editted on: 14/01/2019. For SAP2000 v.20. 
"""

# Titles of each table
title_grid_lines = 'TABLE:  "GRID LINES"'
title_constraint_definitions = 'TABLE:  "CONSTRAINT DEFINITIONS - BODY"'
title_diaphragm_definitions = 'TABLE:  "CONSTRAINT DEFINITIONS - DIAPHRAGM"'
title_joint_coordinates = 'TABLE:  "JOINT COORDINATES"'
title_joint_constraint = 'TABLE:  "JOINT CONSTRAINT ASSIGNMENTS"'
title_joint_restraint = 'TABLE:  "JOINT RESTRAINT ASSIGNMENTS"'
title_joint_elements = 'TABLE:  "OBJECTS AND ELEMENTS - JOINTS"'

title_joint_masses = 'TABLE:  "ASSEMBLED JOINT MASSES"'

title_mat_mech = 'TABLE:  "MATERIAL PROPERTIES 02 - BASIC MECHANICAL PROPERTIES"'
title_frame_sec_def = 'TABLE:  "FRAME SECTION PROPERTIES 01 - GENERAL"'
title_frame_sec_ass = 'TABLE:  "FRAME SECTION ASSIGNMENTS"'
title_frame_release = 'TABLE:  "FRAME RELEASE ASSIGNMENTS 1 - GENERAL"'
title_partial_fix = 'TABLE:  "FRAME RELEASE ASSIGNMENTS 2 - PARTIAL FIXITY"'
title_frame_offset = 'TABLE:  "FRAME INSERTION POINT ASSIGNMENTS"'
title_link_prop = 'TABLE:  "LINK PROPERTY ASSIGNMENTS"'

title_frm_lcl_axs = 'TABLE:  "FRAME LOCAL AXES ASSIGNMENTS 1 - TYPICAL"'
title_frame_conn = 'TABLE:  "CONNECTIVITY - FRAME"'
title_link_lcl_axs = 'TABLE:  "LINK LOCAL AXES ASSIGNMENTS 1 - TYPICAL"'
title_link_conn = 'TABLE:  "CONNECTIVITY - LINK"'

# Delimiter used to separate each entry in the table
s2k_file_delimiter = '   '

# The axis parallel to the vertical direction
s2k_vert_axis = 'Z'

# Symbol generated by s2k to indicate running line
s2k_running_symbol ='_'

# Variable used to check the title of a table
s2k_table_title = 'TABLE'

# Entry titles of title_grid_lines
axis_dir = 'AxisDir'
coord = 'XRYZCoord'
grid_id = 'GridID'

# Entry titles of title_joint_constraint
jnt_cnstrt = 'Joint'
cnstrt = 'Constraint'
typ = 'Type'
body = 'Body'
diaph = 'Diaphragm'

# Entry titles of title_joint_restraint
jnt_rstrt = 'Joint'
u1 = 'U1'; u2 = 'U2'; u3 = 'U3'
r1 = 'R1'; r2 = 'R2'; r3 = 'R3'
yes = 'Yes'     # s2k output to determine constrained DoFs

# Entry titles of title_constraint_definitions
name = 'Name'
ux_cnstrt = 'UX'; uy_cnstrt = 'UY'; uz_cnstrt = 'UZ'
rx_cnstrt = 'RX'; ry_cnstrt = 'RY'; rz_cnstrt = 'RZ'

# Entry titles of title_joint_coordinates and title_joint_elements
jnt_coords = 'Joint'
jnt_elem = 'JointElem'
x = 'GlobalX'; y = 'GlobalY'; z = 'GlobalZ'

# Entry titles of title_joint_masses
jnt_masses = 'Joint'
ux_masses = 'U1'; uy_masses = 'U2'; uz_masses = 'U3'
rx_masses = 'R1'; ry_masses = 'R2'; rz_masses = 'R3'

# Entry titles of title_mat_mech
material = 'Material'
E = 'E1'
G = 'G12'

# Entry titles of title_frame_sec_def
sec_name = 'SectionName'
sec_material = 'Material'
sec_area = 'Area'
sec_Jxx = 'TorsConst'
sec_Izz = 'I33'
sec_Iyy = 'I22'
# UPDATE (12/11/19): The sec_Asz used to be 'AS3' and sec_Asy used to be 'AS2'
sec_Asz = 'AS2'
sec_Asy = 'AS3'

# Entry titles of title_frame_sec_ass
frame_sec = 'Frame'
sect_name = 'AnalSect'

# Entry titles of title_frame_release and title_partial_fix
frame_rel = 'Frame'
yes_rel = 'Yes'
M2I = 'M2I'; M3I = 'M3I'
M2J = 'M2J'; M3J ='M3J'

# Entry titles of title_frame_offset
frame_off = 'Frame'
off_y = 'JtOffsetYI'
off_z = 'JtOffsetZI'

# Entry titles of title_link_prop
link = 'Link'
prop_link = 'LinkProp'

# Entry titles of title_frm_lcl_axs and title_link_lcl_axs
frame_axs = 'Frame'
link_axs = 'Link'
angle = 'Angle'

# Entry titles of title_frame_conn and title_link_conn
frame_conn = 'Frame'
link_conn = 'Link'
joint_i = 'JointI'
joint_j = 'JointJ'
length = 'Length'

#_____________________________________________________________________________#

# Parameters for rot_stiffness.py (not related to converter.py) to calculate
# partial fixity spring stiffness

E_rot_stiff = 2e+8        # Young's modulus (kPa)
alpha_rot_stiff = 1.0     # k_rot's equation parameter

#_____________________________________________________________________________#

# DO NOT EDIT THE FOLLOWING LINES!

# Define helper functions
def data_retriever(s2k_data, table_ttl):
    """ This aux_cnstrtiliary function slice the data with the header 'table_ttl' 
    from the s2k_raw list. If header does not exist, returns an empty list. """
    s2k_raw, table_of_contents = s2k_data
    
    if table_ttl in table_of_contents:
        index = table_of_contents[table_ttl]
        return s2k_raw[index[0] : index[1]]
    else:
        return []